projects:
  app:
    schemaPath: ./src/typeDefs.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: ./src/generated/prisma.graphql
    extensions:
      prisma: books-orm/prisma.yml
